USE [OnlineStore]

CREATE TABLE [Cities]
(
	[CityID] INT PRIMARY KEY IDENTITY(1, 1),
	[Name] VARCHAR(20) NOT NULL UNIQUE,
	CHECK (LEN([Name]) > 1)
)

CREATE TABLE [ItemTypes]
(
	[ItemTypeID] INT PRIMARY KEY IDENTITY(101, 1),
	[Name] VARCHAR(20) NOT NULL UNIQUE,
	CHECK (LEN([Name]) > 1)
)

CREATE TABLE [Customers]
(
	[CustomerID] INT PRIMARY KEY IDENTITY(1001, 1),
	[Name] VARCHAR(20) NOT NULL,
	[Birthday] DATE,
	[CityID] INT NOT NULL FOREIGN KEY REFERENCES [Cities]([CityID])
)

CREATE TABLE [Items]
(
	[ItemID] INT PRIMARY KEY IDENTITY(10001, 1),
	[Name] VARCHAR(20) NOT NULL,
	[ItemTypeID] INT NOT NULL FOREIGN KEY REFERENCES [ItemTypes]([ItemTypeID])
)

CREATE TABLE [Orders]
(
	[OrderID] INT PRIMARY KEY IDENTITY(100001, 1),
	[CustomerID] INT NOT NULL FOREIGN KEY REFERENCES [Customers]([CustomerID])
)

CREATE TABLE [OrderItems]
(
	[OrderID] INT NOT NULL FOREIGN KEY REFERENCES [Orders]([OrderID]),
	[ItemID] INT NOT NULL FOREIGN KEY REFERENCES [Items]([ItemID]),
	PRIMARY KEY([OrderID], [ItemID])
)